config/routes.rb
O2Links::Application.routes.draw do
  resources :charm_items

  get   ':id'.downcase   => 'charm_items#show', constraint: { id: /\d+/ }

  root 'charm_items#index'

end

app/models/charm_item.rb
class CharmItem < ActiveRecord::Base
  self.primary_key = "Name"
  before_save { self.Name = self.Name.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charm_items_controller.rb
class CharmItemsController < ApplicationController
  before_action :set_charm_item, only: [:show, :edit, :update, :destroy]

  # GET /charm_items
  # GET /charm_items.json
  def index
    @charm_items = CharmItem.all.sort_by { |e| e.Name}
  end

  # GET /charm_items/1
  # GET /charm_items/1.json
  def show
    #@str = render_to_string
    redirect_to "http://www.origamiowl.com/PWPShowProduct.ashx?ProgramProductId=#{@charm_item.ProductID}"
  end

  # GET /charm_items/new
  def new
    @charm_item = CharmItem.new
  end

  # GET /charm_items/1/edit
  def edit
  end

  # POST /charm_items
  # POST /charm_items.json
  def create
    @charm_item = CharmItem.new(charm_item_params)

    respond_to do |format|
      if @charm_item.save
        format.html { render action: 'new', notice: 'Charm item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @charm_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @charm_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charm_items/1
  # PATCH/PUT /charm_items/1.json
  def update
    respond_to do |format|
      if @charm_item.update(charm_item_params)
        @charm_item.destroy
        @charm_item = CharmItem.new(charm_item_params)
        @charm_item.save
        format.html { redirect_to :action => 'index', notice: 'Charm item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @charm_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charm_items/1
  # DELETE /charm_items/1.json
  def destroy
    @charm_item.destroy
    respond_to do |format|
      format.html { redirect_to charm_items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_charm_item
      @charm_item = CharmItem.find(params[:id].downcase)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def charm_item_params
      params.require(:charm_item).permit(:Name, :ProductID)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charm_items_helper.rb
module CharmItemsHelper
end

app/views/charm_items/_form.html.erb
<%= form_for(@charm_item) do |f| %>
  <% if @charm_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@charm_item.errors.count, "error") %> prohibited this charm_item from being saved:</h2>

      <ul>
      <% @charm_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name %><br>
    <%= f.text_field :Name %>
  </div>
  <div class="field">
    <%= f.label :ProductID %><br>
    <%= f.number_field :ProductID %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/charm_items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @charm_item %> |
<%= link_to 'Back', charm_items_path %>

app/views/charm_items/index.html.erb
<h1>Listing Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Productid</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @charm_items.each do |charm_item| %>
      <tr>
        <td><%= charm_item.Name %></td>
        <td><%= charm_item.ProductID %></td>
        <td><%= link_to 'Open', charm_item %></td>
        <td><%= link_to 'Edit', edit_charm_item_path(charm_item) %></td>
        <td><%= link_to 'Delete', charm_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Charm item', new_charm_item_path %>

app/views/charm_items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', charm_items_path %>

app/views/charm_items/show.html.erb
<p></p>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ProductID %><br>
    <%= f.text_field :ProductID %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <thead>
    <tr>
      <th>Productid</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.ProductID %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Productid:</strong>
  <%= @item.ProductID %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>O2Links</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Listing tags</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>